version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: movie_app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movie_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
